### ISSUE TITLE
The custom figwheel wrapper causes confusion from expected behavior in CIDER

### ISSUE THREAD

**Issue by runswithd6s** [fulcro-legacy/fulcro-template#11]
While working in Emacs with CIDER, I started a new template application for fulcro without going line-by-line in the fulcro developer guide and assumed that cloning the template, opening `client.cljs` and attempting a `cider-jack-in-cljs` or `cider-jack-in-clj&cljs` would work out of box.

It would be helpful to have a quick reference to this information or a link to the developer guide in the `README.md` file in the root of the project.

**Comment by awkay** [comment]
Gladly take a PR, but I don't use/support emacs.

**Comment by awkay** [comment]
For support you should try the Slack channel `#fulcro`
