### ISSUE TITLE
Need to either fix the demo or more loudly advise away from it

### ISSUE THREAD

**Issue by ExMateria** [fulcro-legacy/fulcro-template#14]
Not sure if this is the place for this. But the demo template is not working. Blame me for not following the developer guide. But I just keep getting 404s anytime I try to do anything with the demo app's components. The error acts like it's in the closure compiler somewhere. I've got to get to bed presently, otherwise I'd go back and  recreate the nightmare that I was running into (I wiped out the repo in anger and started over again using the no-demo version of the template.

Thanks for this framework. I look forward to mastering it and building a great many good things with it!

**Comment by awkay** [comment]
Did you use `lein new`? If you did, this is the wrong repo...
